[package]
name = "rode-editor"
version = "0.1.2"
edition = "2021"
authors = ["Kashyap Sukshavas"]
description = "A lightweight editor built with rust"
license = "GPL-3.0-only"
repository = "https://github.com/kashsuks/rode"
readme = "README.md"
keywords = ["editor", "terminal", "egui"]
categories = ["development-tools"]

[dependencies]
eframe = "0.29"
egui = "0.29"
rfd = "0.14"
image = "0.24"
resvg = "0.29"
usvg = "0.29"
tiny-skia = "0.11"
